const img1 = require('../../assets/p2.jpeg');
const img2 = require('../../assets/p6.jpg');
const img3 = require('../../assets/p3.jpg');
const img4 = require('../../assets/p4.jpg');
const img5 = require('../../assets/p5.jpg');
export const data =
    [
        {
            id: 1,
            uName: 'Ali Khan',
            img: img1,
            message: 'test description dummy text test description dummy ',
            time: 'just now',
            sender: true,
            reciever: false,
        },
        {
            id: 2,
            uName: 'Kareem Rehmaan',
            img: img2,
            message: 'test description dummy text test description dummy text  description dummy text',
            time: '9 mints ago',
            sender: true,
            reciever: false,
        },
        {
            id: 3,
            uName: 'Asad Usmani',
            img: img3,
            message: 'test description dummy text test description dummy text  description dummy text description dummy text  description dummy text description dummy text  description dummy text description dummy text  description dummy text description dummy text  description dummy text',
            time: '9 mints ago',
            sender: false,
            reciever: true,
        },
        {
            uName: 'Ahsan Jilani',
            id: 4,
            img: img4,
            message: 'test description dummy',
            time: 'an hour ago',
            sender: true,
            reciever: false,
        },
        {
            id: 343,
            uName: 'Asad Usmani',
            message: 'test description dummy',
            img: img3,
            isImage: true,
            time: '9 mints ago',
            sender: true,
            reciever: false,
        },
        {
            id: 5,
            uName: 'Farhan Sheikh',
            img: img5,
            message: 'test description dummy text  description dummy text ',
            time: 'an hour ago',
            sender: false,
            reciever: true,
        },

        {
            uName: 'Ahsan Jilani',
            id: 6,
            img: img2,
            message: 'test description dummy',
            time: '3 days ago',
            sender: false,
            reciever: true,
        },
        {
            id: 11,
            uName: 'Ali Khan',
            img: img1,
            message: 'test description dummy text test description dummy text',
            time: 'just now',
            sender: false,
            reciever: true,
        },
        {
            id: 22,
            uName: 'Kareem Rehmaan',
            img: img2,
            message: 'test description dummy text test',
            time: '9 mints ago',
            sender: true,
            reciever: false,
        },
        {
            id: 33,
            uName: 'Asad Usmani',
            img: img3,
            message: 'test description dummy text test description dummy text  description dummy ',
            time: '9 mints ago',
            sender: true,
            reciever: false,
        },
        {
            uName: 'Ahsan Jilani',
            id: 44,
            img: img4,
            message: 'test description dummy',
            sender: false,
            reciever: true,
        },
        {
            uName: 'Ahsan Jilani',
            id: 632,
            img: img2,
            message: 'test description dummy',
            isImage:true,
            time: '3 days ago',
            sender: false,
            reciever: true,
        },
        {
            id: 55,
            uName: 'Farhan Sheikh',
            img: img5,
            message: 'test description dummy text  description dummy text ',
            time: 'an hour ago',
            sender: true,
            reciever: false,
        },

        {
            uName: 'Ahsan Jilani',
            id: 66,
            img: img2,
            message: 'test description dummy',
            time: '3 days ago',
            sender: true,
            reciever: false,
        },
    ]
