//signup actions
export const AUTH_SUCCES = 'AUTH_SUCCES';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOADING = 'AUTH_LOADING';

export const LOGOUT_SUCCES = 'LOGOUT_SUCCES';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';

export const DP_UPLAOD_LOADING = 'DP_UPLAOD_LOADING';
export const DP_UPLAOD_FAILED = 'DP_UPLAOD_FAILED';
export const DP_UPLAOD_SUCCES = 'DP_UPLAOD_SUCCES';
export const DP_UPDATE = 'DP_UPDATE ';

export const SEARCH_USER_LOADING = 'SEARCH_USER_LOADING';
export const SEARCH_USER_FAILED = 'SEARCH_USER_FAILED';
export const SEARCH_USER_SUCCES = 'SEARCH_USER_SUCCES';

export const GET_NOTIFICATIONS_SUCCES = 'GET_NOTIFICATIONS_SUCCES';
export const GET_NOTIFICATIONS_FAILED = 'GET_NOTIFICATIONS_FAILED';
export const GET_NOTIFICATIONS_LOADIND = 'GET_NOTIFICATIONS_LOADING';

export const NOTIFICATIONS_BADGE_SUCCES = 'NOTIFICATIONS_BADGE_SUCCES';
export const NOTIFICATIONS_BADGE_FAILED = 'NOTIFICATIONS_BADGE_FAILED';
export const NOTIFICATIONS_BADGE_LOADIND = 'NOTIFICATIONS_BADGE_LOADING';
export const NOTIFICATIONS_BADGE_CLEAR = 'NOTIFICATIONS_BADGE_CLEAR';

export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILED = 'FOLLOW_USER_FAILED';
export const FOLLOW_USER_LOADIND = 'FOLLOW_USER_LOADING';

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS';
export const GET_CONTACTS_FAILED = 'GET_CONTACTS_FAILED';
export const GET_CONTACTS_LOADIND = 'GET_CONTACTS_LOADING';



